services:
  app:
    image: nazmulhasn/ibadi_service_providing_app:latest
    container_name: ibadi_service_providing_app
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb+srv://car-doctor:car-doctor@cluster0.pyj8wdj.mongodb.net/test?retryWrites=true&w=majority
      - REDIS_HOST=ibadi_service_providing_redis
      - REDIS_PORT=6379
    ports:
      - "6000:6000"
      - "6005:6005"
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: ibadi_service_providing_redis
    restart: always
    ports:
      - '5050:6379'
    volumes:
      - redis-data:/data
    command: ['redis-server', '--appendonly', 'yes']

volumes:
  redis-data:

  # mongo:
  #   image: mongo:7.0
  #   container_name: prisma_project_format_mongo
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: always

# volumes:
#   redis-data:
# mongo-data:
