version: '3.9'
services:
  app:
    image: nazmulhasn/iumi_app:latest
    container_name: iumi_app
    restart: always
    env_file:
      - .env
    environment:
      - DATABASE_URL=mongodb+srv://car-doctor:car-doctor@cluster0.pyj8wdj.mongodb.net/iumi_app?retryWrites=true&w=majority
      - REDIS_HOST=iumi_app_redis
      - REDIS_PORT=6379
    ports:
      - '5000:5000'
      - '5005:5005'
    depends_on:
      - redis
      # - mongo
    expose:
      - '5000'
      - '5005'
  # nginx:
  #   image: nginx:latest
  #   container_name: iumi_app_nginx
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   depends_on:
  #     - app

  # redis:
  #   image: redis:7.2-alpine
  #   container_name: iumi_app_redis
  #   restart: always
  #   ports:
  #     - '5050:6379'
  #   volumes:
  #     - redis-data:/data
  #   command: ['redis-server', '--appendonly', 'yes']

  # mongo:
  #   image: mongo:7.0
  #   container_name: iumi_app_mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   environment:
  #     MONGO_INITDB_DATABASE: iumi_app
  #   volumes:
  #     - mongo-data:/data/db
  # certbot:
  #   image: certbot/certbot
  #   container_name: iumi_app_certbot
  #   restart: always
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot

volumes:
  redis-data:
  # mongo-data:
